### PR TITLE
Improve Elastic Load Balancer compatibility

### PR DESCRIPTION
**Pull request by astronouth7303**
Last November, AWS added the ability for Elastic Load Balancers to also talk to Lambda functions, and the schemas between ELB and APIGW _almost_ match.

This fixes compatibility with ELB.

### CODE REVIEW

**Comment by astronouth7303** [comment]
I don't have any API Gateway stuff I can test this with, primarily because the reason I'm using ELB is because I'm tired of arguing with APIGW.

If this is incompatible with APIGW, we can switch between the forms pretty easily. (It's really obvious from the event and the context if its from ELB or APIGW.)

**Comment by astronouth7303** [comment]
Oh, look, according to https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/ this is break APIGW, so I guess this PR needs a rewrite :sigh:

**Comment by astronouth7303** [comment]
Sorry for dramatically refactoring your code. This just seemed like the least-complex way of supporting both?

I also fixed some issues, I think.

**Comment by astronouth7303** [comment]
Ok, do the maintainers have an opinion on this? Is this ok? Is this something you'd like in the project?

**Comment by slank** [comment]
Sorry I haven't commented on this yet. I definitely think this is a good thing to add. I'm a little wary of the implementation, but I haven't had time to look closely to make any suggestions. I'll try to do that this week.

**Comment by ZoidBB** [comment]
+1 on implementation, +9000 on needing this merged up ASAP -- we're trying to use this in prod to build some small REST services behind an ELB w/Flask, and this fixes the bugs we've run into.

**Comment by slank** [comment]
OK, having taken a look I don't see another obvious approach. Could you add some tests around the selection code?

**Comment by astronouth7303** [comment]
Will do!

**Comment by astronouth7303** [comment]
And done.

**Pull request merged**
